# Generated by Django 5.2.3 on 2025-06-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="comtent",
            new_name="content",
        ),
    ]
