# Generated by Django 5.2.3 on 2025-06-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.CharField(default="C", max_length=10),
        ),
    ]
